using PROYECTO_MONGO_DOTNET.Models.Entidades;
using PROYECTO_MONGO_DOTNET.Services;
namespace PROYECTO_MONGO_DOTNET.Repositories;
public interface IRegistroHoraRepositorio { Task<IReadOnlyCollection<RegistroHoraProyecto>> PorProyectoAsync(string codigoProyecto); Task<IReadOnlyCollection<RegistroHoraProyecto>> ListarAsync(); Task<RegistroHoraProyecto?> ObtenerAsync(string codigoProyecto,string codigoRegistro); Task<decimal> HorasDiaAsync(string empleado,DateTime fecha,string? excluirCodigo=null); Task<bool> ExistenPendientesAsync(string codigoProyecto); Task CrearAsync(RegistroHoraProyecto registro); Task<bool> ActualizarAsync(RegistroHoraProyecto registro); }
public sealed class RegistroHoraRepositorio(SqlContexto db):IRegistroHoraRepositorio
{
    private const string C="Id,CodigoRegistro,CodigoProyecto,CodigoEmpleado,CodigoTarea,Fecha,Horas,Actividad,Estado,RegistradoPor,FechaRegistro,AprobadoPor,FechaAprobacion,ObservacionRevision,CostoHoraAplicado,ModificadoPor,FechaModificacion";
    public async Task<IReadOnlyCollection<RegistroHoraProyecto>> PorProyectoAsync(string p)=>await db.ConsultarAsync<RegistroHoraProyecto>($"SELECT {C} FROM app.RegistroHora WHERE CodigoProyecto=@P ORDER BY Fecha DESC",new{P=N(p)});
    public async Task<IReadOnlyCollection<RegistroHoraProyecto>> ListarAsync()=>await db.ConsultarAsync<RegistroHoraProyecto>($"SELECT {C} FROM app.RegistroHora");
    public async Task<RegistroHoraProyecto?> ObtenerAsync(string p,string r)=>(await db.ConsultarAsync<RegistroHoraProyecto>($"SELECT {C} FROM app.RegistroHora WHERE CodigoProyecto=@P AND CodigoRegistro=@R",new{P=N(p),R=N(r)})).FirstOrDefault();
    public async Task<decimal> HorasDiaAsync(string e,DateTime f,string? x=null)=>await db.EscalarAsync<decimal>("SELECT COALESCE(SUM(Horas),0) FROM app.RegistroHora WHERE CodigoEmpleado=@E AND Fecha>=@Inicio AND Fecha<@Fin AND Estado<>'ANULADO' AND (@X='' OR CodigoRegistro<>@X)",new{E=N(e),Inicio=f.Date,Fin=f.Date.AddDays(1),X=N(x)});
    public async Task<bool> ExistenPendientesAsync(string p)=>await db.EscalarAsync<int>("SELECT COUNT(1) FROM app.RegistroHora WHERE CodigoProyecto=@P AND Estado='PENDIENTE'",new{P=N(p)})>0;
    public async Task CrearAsync(RegistroHoraProyecto x)=>await db.EjecutarAsync("INSERT app.RegistroHora (Id,CodigoRegistro,CodigoProyecto,CodigoEmpleado,CodigoTarea,Fecha,Horas,Actividad,Estado,RegistradoPor,FechaRegistro,AprobadoPor,FechaAprobacion,ObservacionRevision,CostoHoraAplicado,ModificadoPor,FechaModificacion) VALUES (@Id,@CodigoRegistro,@CodigoProyecto,@CodigoEmpleado,@CodigoTarea,@Fecha,@Horas,@Actividad,@Estado,@RegistradoPor,@FechaRegistro,@AprobadoPor,@FechaAprobacion,@ObservacionRevision,@CostoHoraAplicado,@ModificadoPor,@FechaModificacion)",x);
    public async Task<bool> ActualizarAsync(RegistroHoraProyecto x)=>await db.EjecutarAsync("UPDATE app.RegistroHora SET CodigoProyecto=@CodigoProyecto,CodigoEmpleado=@CodigoEmpleado,CodigoTarea=@CodigoTarea,Fecha=@Fecha,Horas=@Horas,Actividad=@Actividad,Estado=@Estado,RegistradoPor=@RegistradoPor,FechaRegistro=@FechaRegistro,AprobadoPor=@AprobadoPor,FechaAprobacion=@FechaAprobacion,ObservacionRevision=@ObservacionRevision,CostoHoraAplicado=@CostoHoraAplicado,ModificadoPor=@ModificadoPor,FechaModificacion=@FechaModificacion WHERE CodigoRegistro=@CodigoRegistro",x)>0;
    private static string N(string? x)=>(x??"").Trim().ToUpperInvariant();
}
